# Generated by Django 3.0.6 on 2020-05-12 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('ratings', models.IntegerField(choices=[(0, 'NO Rating'), (1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=0)),
                ('purchaseId', models.AutoField(primary_key=True, serialize=False)),
                ('productId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
