# Generated by Django 3.0.6 on 2020-05-13 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=250, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchaseId', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetails',
            fields=[
                ('purchaseOrderDetailsId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('productId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Product')),
                ('purchaseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.PurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('ratingId', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField(choices=[(0, 'NO Rating'), (1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=0)),
                ('purchaseOrderDetailsId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.PurchaseOrderDetails')),
            ],
        ),
        migrations.CreateModel(
            name='DerivedProduct',
            fields=[
                ('derivedProductId', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('productId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivedAttributes', to='Products.Product')),
            ],
        ),
    ]
