# Generated by Django 3.0.6 on 2020-05-12 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0002_purchase_purchasedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedProduct',
            fields=[
                ('derivedProductId', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchaseId', models.AutoField(primary_key=True, serialize=False)),
                ('purchaseDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetails',
            fields=[
                ('purchaseOrderDetailsId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('ratingId', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField(choices=[(0, 'NO Rating'), (1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=0)),
                ('purchaseOrderDetailsId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.PurchaseOrderDetails')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='productId',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddField(
            model_name='purchaseorderdetails',
            name='productId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Product'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetails',
            name='purchaseId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='derivedproduct',
            name='productId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Product'),
        ),
    ]
